[tool.vapor]

[environments]
    [environments.py3]
    configuration = "poetry"
    [environments.py3.dependencies]
    python = ">=3.5"
    requests = "@2.20.1"
    nltk = "@3.3"
    beautifulsoup4 = "@4.6.3"

[execution]
    engine = "docker"
    mode = "parallel"
    [execution.configuration]
    tag-prefix = "peterzap"
    base-dockerfile = "Dockerfile"
