[tool.vapor]

[environments]
    [environments.py3]
    configuration = "poetry"
    [tool.poetry.dependencies]
    python = ">=3.6"

[execution]
    engine = "helm"
    [execution.configuration]
        image-repo = "hub.docker.com"
        tag-prefix = "peterzap"
        kubernetes-host = "192.168.99.101"           # minikube ip
        service-type = "Ingress"                     # we can also expose NodePorts
        chart = "example-service"
        config-directory = "~/.vapor-chart-configs"  # the compiled chart configs go here
